site_name: Microscopy Nodes
repo_url: https://github.com/aafkegros/MicroscopyNodes
nav:
  - Home: overview.md
  - Help: faq.md
  - Tutorials:
    - Starting with Microscopy Nodes:
      - 1. First Use: tutorials/1_start.md
      - 2. Loading data: tutorials/2_loading_data.md
      - 3. Data objects: tutorials/3_objects.md
      - 4. Shading: tutorials/4_shading.md
      - 5. Creating output: tutorials/5_creating_ouput.md

    - Extra tutorials:
      - Large datasets: tutorials/large_data.md
      - OME-Zarr troubleshooting: tutorials/ome_zarr_troubleshooting.md
      - Preferences: tutorials/preferences.md
      - Rendering: tutorials/rendering.md
      - Surface smoothing: tutorials/surface_smoothing.md


theme:
  name: material
  font:
    text: Rubik
  logo: figures/logo.svg
  favicon: figures/favicon.svg
  features:
    - navigation.tabs

plugins:
  - include-markdown
  - search
  - macros:
      module_name: mkdocs_macros

markdown_extensions:
  - pymdownx.snippets
  - attr_list
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.details


extra_css:
  - stylesheets/extra_css.css

extra_javascript:
  - javascript/lazy_yt.js 