[tool.poetry]
name = "microscopynodes"
version = "3.0.1"
description = "Loading and handling microscopy data in Blender."
authors = ["Aafke Gros <aafke.gros@embl.de>"]
include = [
    {path = "README.md"}
]
[[tool.poetry.source]]
name = "dailybpy"
url = "https://bradyajohnston.github.io/dailybpy/"
priority = "explicit"

[tool.poetry.dependencies]
python = "==3.13.9"
# bpy = { version = "==5.1.0b", source = "dailybpy" }
bpy = "==5.1.0"
dask = "==2026.1.2"
importlib-metadata = "==8.7.0"
tifffile = "==2026.2.24"
imagecodecs = "==2025.3.30"
zarr = "==3.1.5"
fsspec = "==2026.2.0"
cmap = "==0.7.1"
s3fs = "==2026.2.0"
zmesh = "==1.9.0"
databpy = "==0.7.0"
nodebpy = "==0.17.0"
pydantic = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-snapshot = "*"
imageio = "*"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]
