schema_version = "1.0.0"

id = "microscopynodes"
version = "2.0.0"
name = "Microscopy Nodes"
tagline = "Handling microscopy data in Blender, up to 5D volumes"
maintainer = "Oane Gros <oane.gros@embl.de>"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/oanegros/MicroscopyNodes"

platforms = [
	"macos-arm64",
]
tags = [
	"Import-Export"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:MIT"
]
copyright =[
	"2023-2024 Oane Gros",
]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
	"./wheels/PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/aiohappyeyeballs-2.4.0-py3-none-any.whl",
	"./wheels/aiohttp-3.10.3-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/aiosignal-1.3.1-py3-none-any.whl",
	"./wheels/asciitree-0.3.4.dev1-py3-none-any.whl",
	"./wheels/attrs-24.2.0-py3-none-any.whl",
	"./wheels/click-8.1.7-py3-none-any.whl",
	"./wheels/cloudpickle-3.0.0-py3-none-any.whl",
	"./wheels/dask-2024.8.0-py3-none-any.whl",
	"./wheels/fasteners-0.19-py3-none-any.whl",
	"./wheels/frozenlist-1.4.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/fsspec-2024.6.0-py3-none-any.whl",
	"./wheels/idna-3.8-py3-none-any.whl",
	"./wheels/imagecodecs-2024.6.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/imageio-2.35.1-py3-none-any.whl",
	"./wheels/importlib_metadata-8.4.0-py3-none-any.whl",
	"./wheels/lazy_loader-0.4-py3-none-any.whl",
	"./wheels/locket-1.0.0-py2.py3-none-any.whl",
	"./wheels/multidict-6.0.5-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/networkx-3.3-py3-none-any.whl",
	"./wheels/numcodecs-0.13.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/packaging-24.1-py3-none-any.whl",
	"./wheels/partd-1.4.2-py3-none-any.whl",
	"./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/scikit_image-0.22.0-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/scipy-1.14.1-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/tifffile-2023.4.12-py3-none-any.whl",
	"./wheels/toolz-0.12.1-py3-none-any.whl",
	"./wheels/yarl-1.9.4-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/zarr-2.17.2-py3-none-any.whl",
	"./wheels/zipp-3.20.1-py3-none-any.whl",
]

[permissions]
files = "Importing data files from disk, writing to cache folder"
network = "Loading OME-zarr files from the internet from a given URL"