schema_version = "1.0.0"

id = "microscopynodes"
version = "3.1.2"
name = "Microscopy Nodes"
tagline = "Handling microscopy data in Blender, up to 5D volumes"
maintainer = "Aafke Gros <aafke.gros@embl.de>"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://aafkegros.github.io/MicroscopyNodes/"

platforms = [
	"macos-arm64",
	"windows-x64",
	"linux-x64",
]
tags = [
	"Import-Export"
]
blender_version_min = "5.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright =[
	"2023-2026 Aafke Gros",
]

wheels = [
	"./wheels/aiobotocore-3.9.0-py3-none-any.whl",
	"./wheels/aiohappyeyeballs-2.7.1-py3-none-any.whl",
	"./wheels/aiohttp-3.14.3-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/aiohttp-3.14.3-cp313-cp313-win_amd64.whl",
	"./wheels/aioitertools-0.13.0-py3-none-any.whl",
	"./wheels/aiosignal-1.4.0-py3-none-any.whl",
	"./wheels/annotated_types-0.8.0-py3-none-any.whl",
	"./wheels/attrs-26.1.0-py3-none-any.whl",
	"./wheels/botocore-1.43.56-py3-none-any.whl",
	"./wheels/click-8.4.2-py3-none-any.whl",
	"./wheels/cloudpickle-3.1.2-py3-none-any.whl",
	"./wheels/cmap-0.7.1-py3-none-any.whl",
	"./wheels/dask-2026.1.2-py3-none-any.whl",
	"./wheels/databpy-0.7.0-py3-none-any.whl",
	"./wheels/donfig-0.8.1.post1-py3-none-any.whl",
	"./wheels/frozenlist-1.8.0-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
	"./wheels/frozenlist-1.8.0-cp313-cp313-win_amd64.whl",
	"./wheels/fsspec-2026.2.0-py3-none-any.whl",
	"./wheels/google_crc32c-1.8.0-cp313-cp313-macosx_12_0_arm64.whl",
	"./wheels/google_crc32c-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl",
	"./wheels/google_crc32c-1.8.0-cp313-cp313-win_amd64.whl",
	"./wheels/idna-3.18-py3-none-any.whl",
	"./wheels/imagecodecs-2025.3.30-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/imagecodecs-2025.3.30-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/imagecodecs-2025.3.30-cp313-cp313-win_amd64.whl",
	"./wheels/jmespath-1.1.0-py3-none-any.whl",
	"./wheels/locket-1.0.0-py2.py3-none-any.whl",
	"./wheels/multidict-6.7.1-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/multidict-6.7.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/multidict-6.7.1-cp313-cp313-win_amd64.whl",
	"./wheels/nodebpy-520.0.1-py3-none-any.whl",
	"./wheels/numcodecs-0.16.5-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/numcodecs-0.16.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/numcodecs-0.16.5-cp313-cp313-win_amd64.whl",
	"./wheels/partd-1.4.2-py3-none-any.whl",
	"./wheels/propcache-0.5.2-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/propcache-0.5.2-cp313-cp313-win_amd64.whl",
	"./wheels/pydantic-2.13.4-py3-none-any.whl",
	"./wheels/pydantic_core-2.46.4-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/pydantic_core-2.46.4-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/pydantic_core-2.46.4-cp313-cp313-win_amd64.whl",
	"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
	"./wheels/pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/pyyaml-6.0.3-cp313-cp313-win_amd64.whl",
	"./wheels/s3fs-2026.2.0-py3-none-any.whl",
	"./wheels/six-1.17.0-py2.py3-none-any.whl",
	"./wheels/tifffile-2026.2.24-py3-none-any.whl",
	"./wheels/toolz-1.1.0-py3-none-any.whl",
	"./wheels/typing_inspection-0.4.4-py3-none-any.whl",
	"./wheels/urllib3-2.7.0-py3-none-any.whl",
	"./wheels/wrapt-2.3.0-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/wrapt-2.3.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
	"./wheels/wrapt-2.3.0-cp313-cp313-win_amd64.whl",
	"./wheels/yarl-1.24.5-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/yarl-1.24.5-cp313-cp313-win_amd64.whl",
	"./wheels/zarr-3.1.5-py3-none-any.whl",
	"./wheels/zmesh-1.9.0-cp313-cp313-macosx_11_0_arm64.whl",
	"./wheels/zmesh-1.9.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/zmesh-1.9.0-cp313-cp313-win_amd64.whl",
]

[permissions]
files = "Importing data files from disk, writing to cache folder"
network = "Loading OME-zarr files from the internet from a given URL"
