schema_version = "1.0.0"

id = "microscopynodes"
version = "2.2.1"
name = "Microscopy Nodes"
tagline = "Handling microscopy data in Blender, up to 5D volumes"
maintainer = "Oane Gros <oane.gros@embl.de>"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://aafkegros.github.io/MicroscopyNodes/"

platforms = [
	"windows-x64",
	"linux-x64",
	"macos-arm64",
	"macos-x64",
]
tags = [
	"Import-Export"
]
blender_version_min = "4.4.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright =[
	"2023-2025 Oane Gros",
]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
	"./wheels/PyYAML-6.0.2-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
	"./wheels/aiobotocore-2.23.0-py3-none-any.whl",
	"./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
	"./wheels/aiohttp-3.12.13-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/aiohttp-3.12.13-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/aiohttp-3.12.13-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/aiohttp-3.12.13-cp311-cp311-win_amd64.whl",
	"./wheels/aioitertools-0.12.0-py3-none-any.whl",
	"./wheels/aiosignal-1.3.2-py2.py3-none-any.whl",
	"./wheels/asciitree-0.3.4.dev1-py3-none-any.whl",
	"./wheels/attrs-25.3.0-py3-none-any.whl",
	"./wheels/botocore-1.38.27-py3-none-any.whl",
	"./wheels/click-8.2.1-py3-none-any.whl",
	"./wheels/cloudpickle-3.1.1-py3-none-any.whl",
	"./wheels/cmap-0.6.0-py3-none-any.whl",
	"./wheels/crc32c-2.7.1-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/crc32c-2.7.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/crc32c-2.7.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/crc32c-2.7.1-cp311-cp311-win_amd64.whl",
	"./wheels/dask-2025.5.1-py3-none-any.whl",
	"./wheels/donfig-0.8.1.post1-py3-none-any.whl",
	"./wheels/frozenlist-1.7.0-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/frozenlist-1.7.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/frozenlist-1.7.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/frozenlist-1.7.0-cp311-cp311-win_amd64.whl",
	"./wheels/fsspec-2025.5.1-py3-none-any.whl",
	"./wheels/idna-3.10-py3-none-any.whl",
	"./wheels/imagecodecs-2025.3.30-cp311-cp311-macosx_10_14_x86_64.whl",
	"./wheels/imagecodecs-2025.3.30-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/imagecodecs-2025.3.30-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/imagecodecs-2025.3.30-cp311-cp311-win_amd64.whl",
	"./wheels/imageio-2.37.0-py3-none-any.whl",
	"./wheels/importlib_metadata-8.7.0-py3-none-any.whl",
	"./wheels/jmespath-1.0.1-py3-none-any.whl",
	"./wheels/lazy_loader-0.4-py3-none-any.whl",
	"./wheels/locket-1.0.0-py2.py3-none-any.whl",
	"./wheels/multidict-6.5.1-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/multidict-6.5.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/multidict-6.5.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
	"./wheels/multidict-6.5.1-cp311-cp311-win_amd64.whl",
	"./wheels/networkx-3.5-py3-none-any.whl",
	"./wheels/numcodecs-0.16.1-cp311-cp311-macosx_10_13_x86_64.whl",
	"./wheels/numcodecs-0.16.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/numcodecs-0.16.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/numcodecs-0.16.1-cp311-cp311-win_amd64.whl",
	"./wheels/packaging-25.0-py3-none-any.whl",
	"./wheels/partd-1.4.2-py3-none-any.whl",
	"./wheels/pillow-11.2.1-cp311-cp311-macosx_10_10_x86_64.whl",
	"./wheels/pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pillow-11.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl",
	"./wheels/propcache-0.3.2-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/propcache-0.3.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/propcache-0.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/propcache-0.3.2-cp311-cp311-win_amd64.whl",
	"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
	"./wheels/s3fs-2025.5.1-py3-none-any.whl",
	"./wheels/scikit_image-0.25.2-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/scikit_image-0.25.2-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/scikit_image-0.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/scikit_image-0.25.2-cp311-cp311-win_amd64.whl",
	"./wheels/scipy-1.15.2-cp311-cp311-macosx_10_13_x86_64.whl",
	"./wheels/scipy-1.15.2-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/scipy-1.15.2-cp311-cp311-win_amd64.whl",
	"./wheels/six-1.17.0-py2.py3-none-any.whl",
	"./wheels/tifffile-2025.6.11-py3-none-any.whl",
	"./wheels/toolz-1.0.0-py3-none-any.whl",
	"./wheels/typing_extensions-4.14.0-py3-none-any.whl",
	"./wheels/urllib3-2.5.0-py3-none-any.whl",
	"./wheels/wrapt-1.17.2-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/wrapt-1.17.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/wrapt-1.17.2-cp311-cp311-win_amd64.whl",
	"./wheels/yarl-1.20.1-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/yarl-1.20.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/yarl-1.20.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/yarl-1.20.1-cp311-cp311-win_amd64.whl",
	"./wheels/zarr-3.0.8-py3-none-any.whl",
	"./wheels/zipp-3.23.0-py3-none-any.whl",
]

[permissions]
files = "Importing data files from disk, writing to cache folder"
network = "Loading OME-zarr files from the internet from a given URL"