name: test-addon

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.9'

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with=dev

      - name: Run Tests
        run: poetry run pytest --verbose
